const Products = [
    {
        id: 1,
        brand: "nirave fashion",
        title: "Printed Kantha Cotton Linen Saree",
        color: "White",
        price: 598,
        oldPrice: 1999,
        discount: "70% off",
        img: "1.jpg",
    },
    {
        id: 2,
        brand: "SNH EXPORT",
        title: "Woven Banarasi Silk Blend Saree",
        color: "Red",
        price: 393,
        oldPrice: 2999,
        discount: "86% off",
        img: "2.jpg",
    },
    {
        id: 3,
        brand: "PD CLOTH VILLA",
        title: "Solid/Plain Bollywood Satin Saree",
        color: "Pink",
        price: 476,
        oldPrice: 3099,
        discount: "84% off",
        img: "3.jpg",
    },
    {
        id: 4,
        brand: "PRATYAMFASHION",
        title: "Embellished Bollywood Saree",
        color: "Beige",
        price: 1439,
        oldPrice: 2999,
        discount: "52% off",
        img: "4.jpg",
    },
    {
        id: 1,
        brand: "nirave fashion",
        title: "Printed Kantha Cotton Linen Saree",
        color: "White",
        price: 598,
        oldPrice: 1999,
        discount: "70% off",
        img: "5.jpg",
    },
    {
        id: 2,
        brand: "SNH EXPORT",
        title: "Woven Banarasi Silk Blend Saree",
        color: "Red",
        price: 393,
        oldPrice: 2999,
        discount: "86% off",
        img: "6.jpg",
    },
    {
        id: 3,
        brand: "PD CLOTH VILLA",
        title: "Solid/Plain Bollywood Satin Saree",
        color: "Pink",
        price: 476,
        oldPrice: 3099,
        discount: "84% off",
        img: "7.jpg",
    },
    {
        id: 4,
        brand: "PRATYAMFASHION",
        title: "Embellished Bollywood Saree",
        color: "Beige",
        price: 1439,
        oldPrice: 2999,
        discount: "52% off",
        img: "8.jpg",
    },
    {
        id: 1,
        brand: "nirave fashion",
        title: "Printed Kantha Cotton Linen Saree",
        color: "White",
        price: 598,
        oldPrice: 1999,
        discount: "70% off",
        img: "4.jpg",
    },
    {
        id: 2,
        brand: "SNH EXPORT",
        title: "Woven Banarasi Silk Blend Saree",
        color: "Red",
        price: 393,
        oldPrice: 2999,
        discount: "86% off",
        img: "3.jpg",
    },
    {
        id: 3,
        brand: "PD CLOTH VILLA",
        title: "Solid/Plain Bollywood Satin Saree",
        color: "Pink",
        price: 476,
        oldPrice: 3099,
        discount: "84% off",
        img: "5.jpg",
    },
    {
        id: 4,
        brand: "PRATYAMFASHION",
        title: "Embellished Bollywood Saree",
        color: "Beige",
        price: 1439,
        oldPrice: 2999,
        discount: "52% off",
        img: "2.jpg",
    },
    {
        id: 1,
        brand: "nirave fashion",
        title: "Printed Kantha Cotton Linen Saree",
        color: "White",
        price: 598,
        oldPrice: 1999,
        discount: "70% off",
        img: "7.jpg",
    },
    {
        id: 2,
        brand: "SNH EXPORT",
        title: "Woven Banarasi Silk Blend Saree",
        color: "Red",
        price: 393,
        oldPrice: 2999,
        discount: "86% off",
        img: "6.jpg",
    },
    {
        id: 3,
        brand: "PD CLOTH VILLA",
        title: "Solid/Plain Bollywood Satin Saree",
        color: "Pink",
        price: 476,
        oldPrice: 3099,
        discount: "84% off",
        img: "8.jpg",
    },
    {
        id: 4,
        brand: "PRATYAMFASHION",
        title: "Embellished Bollywood Saree",
        color: "Beige",
        price: 1439,
        oldPrice: 2999,
        discount: "52% off",
        img: "4.jpg",
    },
];

export default Products